### ISSUE TITLE
"Join Slack" link is broken

### ISSUE THREAD

**Issue by mrcolbyrussell** [open-austin/website-v2-vercel#67] opened 2023-04-07 17:56 UTC
Steps to reproduce
==================

1. Visit <https://www.open-austin.org/>
2. Mouse over or tap\* (on mobile) the "Join" menu
3. Click "Join Slack"

Expected results
================

Taken to Slack

Actual results
==============

Heroku application error (for <https://slack.open-austin.org/>)

Additional info
===============

* issue #46 is concerned with with adding this page; nonetheless, it doesn't exist right now
* last night at the AURA joint meetup @lianilychee had to follow up with a remark that the "Join Slack" link is broken right now

The latter is a problem that can be trivially mitigated for the time being by linked directly to the Slack-hosted page at <https://open-austin.slack.com/>.

\* on mobile, "Join" is hidden in a hamburger menu in the top right, so it will need tapped beforehand (consider this step 1.5)

**Comment by lianilychee** [comment] 2023-06-27 05:40
I'm sad to close this excellently written ticket, but the problem is being tracked #46

**Closed as completed by lianilychee** 2023-06-27 05:40 UTC
